### ISSUE TITLE
Autocompleting on Windows any time causes extra newlines at the end of the buffer

### ISSUE THREAD

**Issue by justinwoo** [nwolverson/vscode-ide-purescript#75] opened 2017-06-30 08:48 UTC
Might be related to #52, happens with 0.11.5

Every time I use auto-complete (new import or not), I end up with newlines at the end of my file. Seems to be Windows-only, haven't really seen if this happens with anything else (I don't have a working Emacs or anything else setup on Windows).

**Comment by justinwoo** [comment] 2017-06-30 08:53
This really might just only be me and my messed up setup though. Need to see what happens with other Windows users' setups.

**Comment by natefaubion** [comment] 2017-07-04 15:16
I have a similar problem on Mac. When editing the last line of a file, and invoking autocomplete, it adds an extra newline and the cursor jumps to the end of the file.

**Comment by nwolverson** [comment] 2017-07-04 16:03
The last line seems to be a different issue which I think I've spotted before, unless someone has observed @justinwoo 's problem I assume that in particular is some windows-specific thing to do with newline handling.

**Comment by nwolverson** [comment] 2017-07-05 06:18
@justinwoo I can't reproduce your issue in general (windows, purs 0.11.5, plugin 0.11.1)  - can you confirm if it's the same as the one nate is describing when completing at the end of the file?

**Comment by justinwoo** [comment] 2017-07-05 06:42
No, for me it's anywhere in the buffer... I can try to check more specific stuff later but it's Windows 10 on normal VSCode with purs 0.11.5 and the latest plugin version

**Comment by nwolverson** [comment] 2017-07-05 06:56
Actually I can reproduce, it happens for me if the file has CRLF line endings but not with LF, which somehow my test file had. Cursor ended up in the wrong place too as per discussion in #52.

**Comment by justinwoo** [comment] 2017-07-05 21:23
sigh.. you were right. only happens with CRLF mode and doesn't happen on LF mode...

**Comment by justinwoo** [comment] 2017-07-06 21:27
Definitely worked! Thanks!

Now I have to figure out how to make sure everything actually gets set to LF even though my config says so 😂

**Comment by vladciobanu** [comment] 2018-02-18 20:48
This is still happening with `0.14.0` in `CRLF` mode: whenever adding imports, cursor jumps at end of file (and a newline is added).

**Comment by nwolverson** [comment] 2018-03-04 15:35
I believe this is now properly fixed as of 0.17.0, in `CRLF`

**Closed by nwolverson** 2018-03-04 15:35 UTC
Labels: bug, windows
