### ISSUE TITLE
Enable for vscode.dev?

### ISSUE THREAD

**Issue by mikesol** [nwolverson/vscode-ide-purescript#194] opened 2021-11-11 09:20 UTC
This extension is currently disabled on vscode.dev. However, with a some elbow grease and pixie dust, perhaps it could be enabled? Ie by (gulp) compiling the language server to wasm using asterius (gulp). Worth considering! https://code.visualstudio.com/api/extension-guides/web-extensions#web-extension-enablement

**Comment by nwolverson** [comment] 2021-11-11 09:47
Duplicate of #193.

If somebody gets the PureScript compiler running in the browser it would be worth looking at, but I imagine that is a non-trivial task

**Closed by nwolverson** 2021-11-11 09:47 UTC
Labels: duplicate
