### ISSUE TITLE
Goto Definition is broken

### ISSUE THREAD

**Issue by bfly2000** [nwolverson/vscode-ide-purescript#51] opened 2017-04-13 02:15 UTC
Trying to "go to definition" on 0.8.1 is failing, trying to open the source at /bower_components/../...purs

I've hacked a solution by making the following change to Location.ts, but i doubt this is the right solution:

```js
import { workspace, Position, Location, Uri } from 'vscode';
import * as Path from 'path';

export const mkLocation = (file : string) => (pos: Position) =>  {
    var fullPath = Path.resolve(workspace.rootPath, file)
    return new Location(Uri.file(fullPath), pos); 
}
```

if this is good enough for now i can submit a PR though

**Comment by nwolverson** [comment] 2017-04-13 08:10
I think the issue is probably because the compiler now outputs relative file paths instead of absolute. Can you confirm you're using 0.11.x purs compiler?

(I think I'd make the fix elsewhere, similarly to what we're doing for error reporting).

**Comment by nwolverson** [comment] 2017-04-13 20:33
Published a fix for this (also goto symbol), lmk if any issues

**Closed by nwolverson** 2017-04-13 20:33 UTC
Labels: bug
