### ISSUE TITLE
Autocomplete causes cursor to jump when adding first explicit import

### ISSUE THREAD

**Issue by natefaubion** [nwolverson/vscode-ide-purescript#96] opened 2018-02-19 19:34 UTC
![vscode-cursor-jump-import](https://user-images.githubusercontent.com/144058/36394359-c034164c-1568-11e8-94a6-039abe2b1504.gif)

Only seems to happen on adding the first explicit import. After that it works fine.

**Comment by nwolverson** [comment] 2018-02-19 21:26
Can you try this with some non-comment text at the bottom of the file?

**Comment by natefaubion** [comment] 2018-02-19 21:42
It happens regardless for me. I just used the comment to make it obvious.

**Comment by natefaubion** [comment] 2018-02-19 21:42
Oh maybe it’s only with white space or comments, you mean?

**Comment by nwolverson** [comment] 2018-02-19 21:57
Well nothing works right at the end of files due to compiler positions thing :) But I don't see that this can be related. Don't worry, I know where to look.

**Comment by natefaubion** [comment] 2018-02-19 22:01
Yeah, it always happens to me, even if there's other content.

**Comment by nwolverson** [comment] 2018-02-19 22:06
I can reproduce this. Incidentally happens every time if I have a CRLF file on mac, possibly some whitespace nonsense again...

**Comment by natefaubion** [comment] 2018-02-26 00:17
This is better in the new release since it doesn't jump to the end of the line, but it still inserts a newline.

![import-newline](https://user-images.githubusercontent.com/144058/36648356-6869a7f4-1a47-11e8-81dd-bc1791013e00.gif)

**Comment by nwolverson** [comment] 2018-02-26 07:24
Newline after `map` in the above? You're just selecting the completion option and that appears?

**Comment by natefaubion** [comment] 2018-02-26 14:59
Yes. Happens on first import. Subsequent imports don’t add a new line.

**Comment by nwolverson** [comment] 2018-03-04 15:35
I believe this is more fixed now.

**Closed by nwolverson** 2018-03-04 15:35 UTC
