### ISSUE TITLE
spago support

### ISSUE THREAD

**Issue by jgoux** [nwolverson/vscode-ide-purescript#120] opened 2019-04-04 16:56 UTC
Hello,

would it be possible to apply the same update as https://github.com/nwolverson/atom-ide-purescript to add spago support?

Currently it doesn't find the imported modules.

**Comment by nwolverson** [comment] 2019-04-05 08:25
Oh, `purescript.addSpagoSources` exists but the LSP dependency needs bumped

**Comment by m1574b34r** [comment] 2019-04-17 23:55
@nwolverson Sorry, new user here, do you mean that there's something easy that users can do to make this work?

It would be nice to use Spago. I tried adding the `purescript.addSpagoSources: true` option, didn't seem to make a difference. I am getting the same behaviour as in #121 so it's not clear to me what the problem is.

It would be great to have a small paragraph on getting set up with each build tool in the main README!

**Comment by nwolverson** [comment] 2019-04-18 10:12
Maybe @Dretch (who added the spago support to the language server) can comment, did you get this working? I thought I had missed updating the purescript-language-server dependency in this extension, but actually this has been published to the marketplace some time ago already, I just didn't push the commits. 

However "Currently it doesn't find the imported modules." may mean many things, "addSpagoSources" merely enables goto definition, as with other build tools you will need to build your project before stuff lights up in vscode, you can do that externally or set the build tool to "spago build -- --json-errors" per https://github.com/nwolverson/purescript-language-server/issues/43

I'd certainly welcome documentation PRs

**Comment by jgoux** [comment] 2019-04-18 12:03
Indeed spago is in fact supported!

In my case, I installed purescript and spago as local npm dependencies. Here are the options I have to activate to enable the support : 
```json
{
  "purescript.addSpagoSources": true,
  "purescript.addNpmPath": true,
  "purescript.buildCommand": "spago build -- --json-errors"
}
```

**Comment by m1574b34r** [comment] 2019-04-19 04:40
Ah yes, for me too with those settings, if I `npm i purescript spago` in the project directory and then `Restart/reconnect purs IDE server` in VS-Code, then I can build with Spago from within VS-Code and see the types and whatnot. :-)

I already had `purescript` and `spago` installed globally in my `PATH` though. I guess this extension could check there too?

**Comment by Sir4ur0n** [comment] 2019-05-16 11:51
FYI using `Restart/Reconnect purs IDE server` didn't work for me, I had to restart VS Code for these changes to take effect.

**Comment by nwolverson** [comment] 2019-07-02 12:33
Closing as skimming back everyone seemed to suggest this is working. Please open a specific issue if there's something that can be improved

**Closed by nwolverson** 2019-07-02 12:33 UTC

**Comment by psylinse** [comment] 2020-03-27 19:23
If anyone is running into the issue `Invalid option '--json-errors'`, the build command for `spago` is now:

`spago build --purs-args '--json-errors'`
